### ISSUE TITLE
Where to get zinc_data_with_bracket_original?

### ISSUE THREAD

**Issue by LRParser** [tsudalab/ChemTS#1]
Is it possible to upload this source data to the repo and just load it using a relative path? I can't get past this error:
```
  File "/home/joe/ChemTS/train_RNN/make_smile.py", line 157, in zinc_data_with_bracket_original
    f = open('/home/yang/LSTM-chemical-project/data/250k_rndm_zinc_drugs_clean.smi', 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/yang/LSTM-chemical-project/data/250k_rndm_zinc_drugs_clean.smi'
```

Alternately can you provide a link to where to get this data?
I am trying to run:
python train_RNN.py

**Comment by yangxiufengsia** [comment]
Hi  @LRParser , thanks for reporting this. The source data is available at /ChemTS/data/250k_rndm_zinc_drugs_clean.smi.   Or you can directly download it from [this site](https://github.com/mkusner/grammarVAE/tree/master/data).  I will change to using a relative path soon.

The path has been changed, please re-run: python train_RNN.py.
