### ISSUE TITLE
HOMO/LUMO and Energy Prediction

### ISSUE THREAD

**Issue by weiwen6** [tsudalab/ChemTS#10]
Hi,

Thank you so much for sharing this wonderful project. It is truly very interesting. Can you please provide a tutorial about how to calculate the HOMO/LUMO and Energy Prediction optimization and generation that you described?

Thanks

**Comment by yangxiufengsia** [comment]
Hi, 
There are several methods can calculate the HOMO/LUMO and Energy:
1) You can make a regression model by using  the available training data(prepared data with smiles, homo/lumo, energy).  Then you can replace the rdkit with trained regression model to optimize homo/lumo and energy during molecule generation. 

2) you can use DFT to calculate  HOMO/LUMO and Energy properties. And replace rdkit with DFT, please check this paper: https://pubs.acs.org/doi/10.1021/acscentsci.8b00213. 

Hope this can help you.
