### ISSUE TITLE
Print Statements Don't work in Python 3.6

### ISSUE THREAD

**Issue by LRParser** [tsudalab/ChemTS#2]
FYI there are a few prints statements that didn't get commented out, and cause things to break in Python 3.6. I've attached a small patch file (you can 'git apply patch.txt') in case you want to make things 3.6 compatible.
[patch.txt](https://github.com/tsudalab/ChemTS/files/1412176/patch.txt)

**Comment by LRParser** [comment]
Also fixed a small issue where CSV reader had filed opened in binary mode (needed to be text) here:
```
f = open('../data/250k_rndm_zinc_drugs_clean.smi', 'r')
```

**Comment by yangxiufengsia** [comment]
@LRParser thanks for helping solve this issue. I have fixed this by using your patch.txt.
